version: "3.8"

services:
  nginx-proxy:
    image: nginx:alpine3.19
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - './config:/etc/nginx:ro'
      - './certs:/etc/nginx/certs:ro'
    env_file:
      - path: web.env
        required: true
