version: "3.8"

services:
  reverse-proxy:
    image: nginx:local
    container_name: reverse-proxy
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - './certs:/etc/nginx/certs:ro'
